<?php
/**
 * Internal MAXAI chat endpoint.
 *
 * Loaded by wp-content/mu-plugins/maxai-loader.php.
 */

if (!defined('ABSPATH')) {
    exit;
}

if (defined('MAXAI_CHAT_ENDPOINT_BOOTSTRAPPED')) {
    return;
}

define('MAXAI_CHAT_ENDPOINT_BOOTSTRAPPED', true);

function maxai_get($key, $fallback = null) {
    if (defined($key) && constant($key)) {
        return constant($key);
    }

    $env = getenv($key);
    if (!empty($env)) {
        return $env;
    }

    $opt = get_option(strtolower($key));
    if (!empty($opt)) {
        return $opt;
    }

    return $fallback;
}

add_action('wp_ajax_nopriv_maxai_chat', 'maxai_handle_chat');
add_action('wp_ajax_maxai_chat', 'maxai_handle_chat');

function maxai_handle_chat() {
    ob_start();

    $apiKey = maxai_get('OPENAI_API_KEY');
    if (!$apiKey) {
        ob_end_clean();
        wp_send_json_error([
            'error' => 'invalid_api_key',
            'detail' => 'API Key not configured in server environment.',
        ], 401);
    }

    $userMsg = isset($_POST['message']) ? sanitize_text_field($_POST['message']) : '';
    if ($userMsg === '') {
        ob_end_clean();
        wp_send_json_error(['error' => 'missing_message'], 400);
    }

    $model = 'gpt-4.1-mini';
    $vsId = maxai_get('MAXAI_VECTOR_STORE_ID');

    $instructions = 'You are the Maximised AI assistant. Answer using knowledge base if possible. Be concise.';

    $payload = [
        'model' => $model,
        'input' => [
            ['role' => 'system', 'content' => $instructions],
            ['role' => 'user', 'content' => $userMsg],
        ],
    ];

    if ($vsId) {
        $payload['tools'] = [[
            'type' => 'file_search',
            'vector_store_ids' => [$vsId],
        ]];
        $payload['tool_choice'] = 'auto';
    }

    $resp = wp_remote_post('https://api.openai.com/v1/responses', [
        'headers' => [
            'Authorization' => 'Bearer ' . $apiKey,
            'Content-Type' => 'application/json',
        ],
        'body' => wp_json_encode($payload),
        'timeout' => 45,
        'data_format' => 'body',
    ]);

    ob_end_clean();

    if (is_wp_error($resp)) {
        wp_send_json_error([
            'error' => 'upstream_error',
            'detail' => $resp->get_error_message(),
        ], 502);
    }

    $code = wp_remote_retrieve_response_code($resp);
    $body = wp_remote_retrieve_body($resp);
    $json = json_decode($body, true);

    if ($code !== 200) {
        wp_send_json_error([
            'error' => 'openai_error_' . $code,
            'detail' => $json['error']['message'] ?? 'Unknown upstream error',
        ], $code);
    }

    $reply = '';
    if (!empty($json['output'][0]['content'])) {
        foreach ($json['output'][0]['content'] as $content) {
            if (isset($content['text'])) {
                $reply .= $content['text'];
            }
        }
    }

    if ($reply === '') {
        wp_send_json_error([
            'error' => 'empty_response',
            'detail' => 'No text generated by AI.',
        ], 500);
    }

    wp_send_json_success(['reply' => trim($reply)]);
}
